### PR TITLE
Version 9.40

### PR DESCRIPTION
**Pull request by ladislav-zezula**

### CODE REVIEW

**Comment by AMDmi3** [comment]
Was this indended to be a breaking change? Both consumers of stormlib in FreeBSD (smpq and wargus) fail to build with 9.40, complaining on GetLastError

```
/work/usr/ports/games/wargus/work/wargus-3.3.2/wartool.cpp:513:13: error: use of undeclared identifier 'GetLastError'; did you mean 'SErrGetLastError'?
```
