### PR TITLE
Fix non-static builds

### LINKED ISSUE #420: Auto-link variable names not in sync
It seems ``STORMLIB_NO_AUTO_LINK`` was changed to ``__STORMLIB_NO_STATIC_LINK__`` [here](https://github.com/ladislav-zezula/StormLib/commit/d1bf5e1c71af432ccc24371a3611dc33edb7361f#diff-08b5eee07685baff3f971c9ec9cbb70f65363f1d296df587bb030e5a27b90dd8)

But not updated in [CMakeLists.txt#L349](https://github.com/ladislav-zezula/StormLib/blob/master/CMakeLists.txt#L349)

Additional note: use of double underscores (or a leading underscore followed by capital letter) is bad practice: https://en.cppreference.com/w/c/language/identifier.html#Reserved_identifiers

### LINKED ISSUE #421: SFileAddListFileEntries not present in non-static lib files
When compiling non-statically the SFileAddListFileEntries method seems not to be present in the resulting .lib file, leading to a classic linker error:
`error LNK2019: unresolved external symbol SFileAddListFileEntries`

Static compilation is fine; I think it's the lack of presence in DllMain.def for windows (and possibly a lack of presence in StormLib.exp for mac builds).

### PR DESCRIPTION
**Pull request by TheNitesWhoSay**
- Update auto-link variable to match the updated name in StormLib.h - fixes #420 
- Add SFileAddListFileEntries to the exported symbols - fixes #421

### CODE REVIEW

**Comment by TheNitesWhoSay** [comment]
Tested & this fixed the linker issues in my build (which in turn is using vcpkg+cmake to build&link to StormLib); ready for review.
